version: '3.8'
services:
    db:
        image: postgres:13-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
    db_migration:
        image: "groosha/telegram-minesweeper-bot:${IMAGE}"
        restart: "on-failure"
        depends_on:
            -   db
        environment:
            -   DB_HOST
            -   DB_PORT
            -   DB_NAME
            -   DB_USER
            -   DB_PASS
        command: sh -c "python -m alembic upgrade head"

    bot:
        image: "groosha/telegram-minesweeper-bot:${IMAGE}"
        stop_signal: SIGINT
        restart: "on-failure"
        env_file: .env
        depends_on:
            - db
            - db_migration


volumes:
    postgres_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './postgres_data'
