version: '3.8'
services:
    redis:
        image: redis:6.0-alpine
        restart: "unless-stopped"
        environment:
            - REDIS_HOST
        volumes:
            # don't forget to put redis.conf to redis_config directory!
            - "/path/to/bombsweeper/redis_config:/usr/local/etc/redis"
            - "/path/to/bombsweeper/redis_data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    db:
        image: postgres:13-alpine
        restart: "unless-stopped"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - "/path/to/bombsweeper/postgres_data:/var/lib/postgresql/data"
    db_migration:
        image: "groosha/telegram-bombsweeper-bot:${IMAGE}"
        restart: "on-failure"
        depends_on:
            -   db
        env_file: .env
        command: sh -c "python -m alembic upgrade head"
    bot:
        image: "groosha/telegram-bombsweeper-bot:${IMAGE}"
        stop_signal: SIGINT
        restart: "unless-stopped"
        env_file: .env
        depends_on:
            - db
            - db_migration
            - redis
