"""initial

Revision ID: 9c6a5ff6a477
Revises: 
Create Date: 2021-08-26 23:28:50.428772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gameshistory',
        sa.Column('game_id', postgresql.UUID(), nullable=False),
        sa.Column('played_at', sa.DateTime(), nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('field_size', sa.Integer(), nullable=False),
        sa.Column('victory', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameshistory')
    # ### end Alembic commands ###
